# Generated by Django 4.1 on 2022-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=300)),
                ('Nombre', models.CharField(max_length=300)),
                ('Correo', models.CharField(max_length=30)),
            ],
        ),
    ]
